### ISSUE TITLE
Query regarding Multithreading the yuma123

### ISSUE THREAD

**Issue by sivaraman-g** [vlvassilev/yuma123#11]
Hi vlvassilev,

I have below query.

Is yuma123  supported with multithreading(lock,unlock) ?
Is it possible to create multiple threads of yuma123? are the shared memory handled properly ?

Thanks in advance.

Regards,
Sivaraman G

**Comment by vlvassilev** [comment]
It is possible to use yuma123 in multi thread context but there is no implicit locking and unlocking of resources part of the API. It depends what your intended multi thread design goal is. For example netconfd has a single event entry point (a UNIX select call) for all events protocol data IO, timer or user events (in case you want to add any). Depending on your design requirements you can add lock,unlock there so that you can add extra threads accessing the data tree while the main server thread is idle. With other designs you might need to do more then that.
