### ISSUE TITLE
Can other NBIs alter Netconf programmed config ?

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#15]
Hi,

1) Is it possible for other Northbound Interfaces such as CLI, SNMP can alter the config which was programmed by Netconf ?

2) If so, would the controller be notified for the configuration changes ?

Thanks,
__kals__

**Comment by vlvassilev** [comment]
Hi,

Since NETCONF has a superior transactional properties it makes sense to use it as the root solution for maintaining configuration. If you do not make the cli tools aware of NETCONF you can't expect the system to have transactional properties. yangcli is using NETCONF SNMP agents can also use NETCONF, web interface services can also use N/ETCONF e.g. libapache2-mod-yangrpc-example. I can not think of another alternative that interoperate in a sane way.

Vladimir
