### ISSUE TITLE
Asynchronous validation / commit callbacks 

### ISSUE THREAD

**Issue by elena-604** [vlvassilev/yuma123#32]
Hello,
In our system we need to do some extra validation and pre-commit processing that requires asynchronous communication with the target components. Is it possible to use the async validation callbacks and what would be the best way to achieve this?

Regards,
Elena

**Comment by vlvassilev** [comment]
Hi,

Depending on what your problem is there are different solutions. RPCs (<commit> among others) are obviously synchronous. notifications can provide means of asynchronous communication. Better designs put the asynchronous semantics in the modules semantics (e.g. transactional configuration with operational data reflecting the actual state of the device). Usually the right solution does not require anything more then the standard behavior of the netconfd server. If you need to do something fancy you are probably working around some problem elsewhere. That is as much I can say from the level of detail you provided.

Vladimir

**Comment by vlvassilev** [comment]
.. for communication with devices generating asynchronous events (e.g. interrupts)  you can use your own socket communication protocol modifying the yuma select call and adding custom handler or you can use YANG/NETCONF model that is not visible to the regular user that sends RPCs informing or reacts to notifications.

**Comment by elena-604** [comment]
Thanks Vladimir for your reply. 
Here is a bit more details: we have a multi-device chassis managed by NETCONF. We need to support multiple concurrent NETCONF sessions with alarms/notifications. 
Configuration maybe quite large and might take some time to validate and apply to all devices. If we have to use synchronous communication to configure all the target devices the transaction will block for a while until everything is complete. As part of callbacks we can implement collecting all the responses back, handle watchdog if needed, etc,  before the callback returns. But during this time all notifications will be blocked as well as all other sessions will not be able to do anything, even any "get" requests - that is undesirable for this system.
 
Please confirm that my understanding is correct. Are there any ways to workaround these limitations?

Thanks,
Elena

**Comment by vlvassilev** [comment]
Making operation that is by design synchronous asynchronous will not solve the problem. It will likely create more problems. The commit of a configuration is in the trivial case transactional command that completes immediately. In your case it is the submission of a plan. This can launch a process that should progress with the plan and if your model is done right it will report the actual state, alarms etc. while progressing with the plan. I have the following example. You have a model of a ship where you can configure desired coordinates and commit the configuration. With the approach with delaying the reply of the commit message the commit will complete when the ship arrives at its destination. The correct alternative of course would be to accept the configuration and start sailing updating coordinates, engine status, temperature etc. as operational state data changes and notifications are sent.

The usual methods for solving problems like splitting the problem (have 2 separate netconfd servers one handling big configurations one having low latency and specialized in sending notifications) are always available.

**Comment by vlvassilev** [comment]
... as of time for validation of configuration committed to managed NETCONF nodes I have had similar problem that was resolved nicely by the introduction of preliminary validation of candidate that actually is not done when you do the actual 'commit'. And if you do all those in parallel send the 1000 commit RPCs and only then wait for the 1000 replies you are down to the delay of the slowest of the devices. Of course this again has the possibility of device not being available.

I am throwing in philosophical points which might or not apply to your design.

**Comment by elena-604** [comment]
Hi Vladimir, 
Can you please elaborate a bit more about the idea of having 2 separate netconfd servers. Let's say we want to have one for configuration and the second one is specialized in notifications only. How would they co-exist? They will be using different ports, but they need to use the same DB, so they need to communicate and share data. Please provide your design suggestions.
Thanks,
Elena

**Comment by vlvassilev** [comment]
If validation delay is the problem and sending notifications during ongoing validation is what you need you have to change the dispatcher so you can write to the sessions from another thread. The simple code of the current dispatcher is a good starting point for doing that but making a general solution will probably require some thought.

You can achieve the same without modifying the dispatcher code if you can receive notifications on a different channel e.g. another instance of netconfd that does not spend time validating configuration upon 'commit'.

If the I/O delay in a commit is the problem then you have a situation you can probably solve by offloading the I/O load to parallel netconfd instances connected to the frontend 'controller' instance as southbound nodes. You would need some interprocess communication YANG models not available/advertised to the regular user and glue logic clients to translate configuration data and notifications to RPCs and vice versa so that you can use NETCONF for interprocess communication.

I am not sure what the exact design limitations are .. it might be possible to solve them by optimizing the validation process or the commit I/O delays too.
