### ISSUE TITLE
Installing different versions of both yuma123(2.10 version) and openyuma-master(2.3 version) will it create any problem with duplicate files to start yuma123 server ?

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#35]
Hi,

I have installed a different version of both yuma123_2_10 and openyuma-master_2.3in one linux machine. after installing both, I have observed few yang files are duplicated. Same yang files are present in /usr/share/yuma/modules/netconfcentral/ and /usr/share/yuma/modules/yuma123/ folder. Due to this, the netconf server is not starting. 
As per my understanding, the openyuma-master_2.3 package installing some dependent yangs in netconfcentral folder but the same yangs are installed by yuma123_2_10 package in /usr/share/yuma/modules/yuma123/ 
is this understanding correct?

**Comment by vlvassilev** [comment]
There could be files with the same name but they have different namespaces.

One of the issues fixed in yuma123-2.11 was the module search algorithm. In yuma123-2.10 and the original yuma the first module found is used instead of searching the full path list and using the most recent version (in case of unversioned module import) which creates problems. I can recommend using yuma123-2.11 instead of 2.10 if you really want to have a module directory which has modules from older yuma versions.

**Comment by santhoshmaddikera** [comment]
Thanks for your response.

After installing Openyuma-master_2.3 and yuma123_2.10 below files are having the same namespaces.
/usr/share/yuma/modules/netconfcentral/yuma-netconf.yang 
/usr/share/yuma/modules/yuma123/yuma123-netconf.yang 

yuma-netconf.yang is generated by Openyuma-master_2.3
yuma123-netconf.yang is generated by yuma123_2.10.

I believe different versions of openyuma installation in same Linux machine causing the issue during netconf server startup.

**Comment by vlvassilev** [comment]
yuma123-netconf.yang and yuma-netconf.yang have the same  "urn:ietf:params:xml:ns:netconf:base:1.0" namespace since they "overload" the ietf-netconf@2011-06-01.yang It will cause problem if you load both of them.

Is there any reason you need to have Openyuma-master_2.3 and yuma123_2.10 and can't just install 2.11.

**Comment by santhoshmaddikera** [comment]
@vlvassilev 
We are using yuma123_2.10 version since yangdump tool is not present in yuma123_2.10, we are using Openyuma-master_2.3 only for yangdump tool. On installation of both Openyuma-master and yuma123 generating duplicate files. To avoid duplicate file with same namespace generation we did few changes in Openyuma-master_2.3 Makefiles such that when we install Openyuma-master_2.3 only yangdump tool related files will be installed. Please confirm this can be done.
Please find attached diff and Request you to please review the code changes, 
[OPENYUMA_2.3-PATCH.docx](https://github.com/vlvassilev/yuma123/files/2478562/OPENYUMA_2.3-PATCH.docx)

**Comment by vlvassilev** [comment]
I really do not see the problem with using the two on separate installations or you can provide module paths and not use the default /usr/share/module/yuma. I do not use yangdump for template generation because it is slowing me down and generates often unnecessary code. After you manage to figure the basics of the API you do not need to use templates. But if you need to you can. The templates generated with any version of yangdump will compile with the newest yuma123 so just try 2.11 instead of 2.10.

**Comment by santhoshmaddikera** [comment]
What are the Major differences between 2.10 and 2.11 versions ?

**Comment by vlvassilev** [comment]
A comprehensive testsuite was introduced that was used to improve conformance and stability. There are also other features. The CHANGELOG file contains a summary of the major differences. Also comparing the code and the commit log should give detailed overview.
