### ISSUE TITLE
Integration user applications with yuma123 NETCONF server

### ISSUE THREAD

**Issue by shashanksprasad** [vlvassilev/yuma123#36]
Hi,
I am new to yuma123 from the user perspective.
I have 2 questions:

1/
I would like to integrate the yuma123 NETCONF server implementation into my application module, such that it runs from the integrated application threads/process.

Essentially, I am exploring options to NOT run as a daemon process, but as a library of the application.
For example, integrate integrate the "IO server loop for the ncxserver socket" (agt_ncxserver_run) of the  yuma123 NETCONF into the application.

Is this approach reasonable?

2/
I would the user applications to know which attribute(s) have changed when the running configuration has changed, or the candidate configuration has been committed.

At present, my understanding is that that NETCONF server shall write the latest configuration into a 'xml' file. And, a mechanism needs to exist to inform the user application (eg. SIGHUP or alternate mechanisms). The user application needs to "diff" the running version from the new version of configuration and apply it.

The above works good for user application which can afford to restart. However, for applications with dynamic updates, the precise attribute(s) which have changed needs to be known.

Would u help how this would be possible?

Thanx.
Shashank

**Comment by vlvassilev** [comment]
Hi,

1. I guess this is doable since the code is not dependent on any scheduler functionality except the simple select loop that should run OK in multithread application. If you have application that can benefit from this it should be an option.

2. One alternative option is to have a client NETCONF application with subscription (see create-subscription) receiving notifications upon commit. Then it can read the running configuration and apply it.

**Comment by vlvassilev** [comment]
Yes. This is a simple usecase. You can send SIGHUP in an AGT_RPC_PH_POST_REPLY callback. It is called after the file save operation - netconf/test/netconfd/agt-commit-complete/test_agt_commit_complete.c
