### ISSUE TITLE
How to merge different yang modules libraries and load into the netconf server?

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#43]
Hi,

I want to merge multiple modules libraries into the single library. let say, interface.so, pw.so, l2vpn.so. PHB.so etc.. all these modules I want to load using the single  ".so" file. 

I am calling other module function from one module, since both the modules having different  ".so" files, while loading the module I am getting undefined reference to <function-name>. 

could you please share your valuable suggestion. 

Regards,
Santhosh

**Comment by vlvassilev** [comment]
Well if you have common symbols (e.g. common functions or global variables) it is best to move them to a shared library that is installed in standard shared library location so that the symbols are resolved. Your SIL modules should not depend on symbols defined in another SIL. There is no problem building a shared library even if it is for a single common function or global variable and IMO this is the right way to solve the problem.
