### ISSUE TITLE
malloc-failed issue after opration-failed

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#45]
Hi,

I am using candidate and running database.

When I do commit for my config in yangcli, due to some error config I am getting operation failed. 
After that, I am configuring with correct values and committing again. At this time  I am facing malloc-failed issue continuously for all commits.
due to that, I am not able to proceed with commits. Could please help me on this issue.

we are using openyuma 2.2 version. we are planning to upgrade. before that, we want to fix this issue. 

Regards,
Santhosh

**Comment by vlvassilev** [comment]
The bug you are experiencing is most likely solved in the current yuma123 code. In order to make reproduction of issues deterministic there is a framework for writing testcases e.g. https://github.com/vlvassilev/yuma123/tree/master/netconf/test/netconfd and https://github.com/vlvassilev/yuma123/tree/master/netconf/test/yangcli 

I can only support problems that are reported with a testcase that fails in the latest snapshot.
