### ISSUE TITLE
How do I access datastore from a SIL callback?

### ISSUE THREAD

**Issue by elena-604** [vlvassilev/yuma123#47]
Hello,
1. I am having troubles to find a function (API) to get value from DB by XPATH from my callback function.
I believe I saw API that looked something like this:
const val_value_t *
  agt_val_get_data (ncx_cfg_t  cfgid,
                    const xmlChar *defpath,
                    status_t *retres);     
But I could not find it in the latest code.

2. I will also need an API to access value of parameter in the incoming message for validation reason. Can I use the following function for this purpose?
/********************************************************************
* FUNCTION agt_get_parmval
*
* Get the identified val_value_t for a given parameter
* Used for error purposes!
* INPUTS:
*    parmname == parameter to get
*    msg == incoming rpc_msg_t in progress
*
* RETURNS:
*    status
*********************************************************************/
extern const val_value_t *
    agt_get_parmval (const xmlChar *parmname,
		     rpc_msg_t *msg);

Regards,
Elena

**Comment by vlvassilev** [comment]
1. xpath_find_val_target - parsing the Xpath is slower then crawling the data instance three ... IMO this is almost never a real problem. Usage:

```
res = xpath_find_val_target(config_val, NULL/*mod*/, "/interfaces/interface[name='xe1']/scheduler", &scheduler_val);
res = xpath_find_val_target(scheduler_val, NULL/*mod*/, "gate-controllers/gate-controller[id='b0']", &gate_controller_val);
res = xpath_find_val_target(root_val, ietf_system_mod/*mod*/,"/sys:system/sys:hostname", &hostname_val);
```
2. You can but I would recommend using the val_ functions directly in this case:
`val =  val_find_child(msg->rpc_input, val_get_mod_name(msg->rpc_input), parmname);`

**Comment by santhoshmaddikera** [comment]
HI,

I am disabling candidate database and using only running. in this case I want to access the value of an object in the SIL function of another object in the validation phase itself. Both the  object which is being accessed is not finished commit phase.

For Example:
I am pushing XML in a single rpc in below order.
<A> 10 </A>
<B> 20 </B>
<C> 30 </C>
<D> 40 </D>
<E> 50 </E>
<F> 60 </F>

Now while in "E" validation phase SIL function, I want to access "B" element value.

As per my observation, since candidate database is disabled and XML elements are still in the validate phase, not possible to fetch the value of "B" from openyuma DB in "E" SIL function. 
Is this understanding correct?

Is there any specfic API that can used inside the SIL function to access a object value in the Validate phase(i.e no object values are stored/commited in the openyuma DB) ?

In the previous answer, in point 2 you have mentioned to use api val_find_child() . But, the input passed to the api is rpc_input. In validation SIL function, the rpc_input will not be available. only the particular node new_val, cur_val will be available. 

Regards,
Santhosh.
