### ISSUE TITLE
Development of "ietf-routing.c" to interact with routing system interface

### ISSUE THREAD

**Issue by vggonzalez** [vlvassilev/yuma123#56]
Hi,

The issue treated here is about the development of a C module which allows yuma/netconfd to interact with a system's routing interface. The yang module it will be developed upon is "ietf-routing@2018-03-13.yang" [https://tools.ietf.org/html/rfc8349#].

Regards.

**Comment by vlvassilev** [comment]
The module implementing ietf-network-bridge-openflow SIL to control OpenFlow device according to the ietf-network-bridge-* draft modules can be used as template. You can start by cloning the [ietf-network-bridge](https://github.com/vlvassilev/yuma123/tree/master/example-modules/ietf-network-bridge) example to ietf-routing SIL example. Then do renaming and replace the openvswitch code with calls to system("/usr/sbin/route ...");  
Some milestones:
1. All YANG modules are loaded and example configuration with a sample topology in  is created in mininet ... starting netconfd servers on the routing nodes and configuring them so that ping propagates across several hops. The configuration should be accepted and validated but the actual handling in the SIL (edit callback) left for step 2.
2. Actually implementing the edit callback figuring new,deleted and modified routes and calling the correct routing commands to update the  routing tables. The mininet testcase from should now actually forward the ping packets to their destinations.

**Comment by vlvassilev** [comment]
Lets pick a topology we will be testing. How about this:
```
     +-------+   p0 +-------+ p1   +-------+      +-------+
    | host0 |------|  rt0  |------|  rt1  |------| host1 |
    +-------+      +-------+      +-------+      +-------+
                     p2|
                   +-------+
                   |  rt2  |
                   +-------+
                       |
                   +-------+
                   | host2 |
                   +-------+
```

To complete step 1 you need a python script starting mininet and running netconfd with correct arguments on all 3 rt* nodes. Do you need help doing this?

Then you need to create the configurations for each rt* node before pinging host1 and host2 from host0 to validate the setup. All this can be done in a single python script first instantiating the topology with mininet then configuring the NETCONF nodes with python-tntapi.

**Comment by vggonzalez** [comment]
I was thinking on creating the virtual network with some other virtualization software like VirtualBox and generating ietf-routing.c's template with yangdump, and then editting it.
Would that be ok?

**Comment by vlvassilev** [comment]
yangdump generates a template using brute force resulting in very long definitions and ugly code - as with any auto-generated C code. I still think it would be better to take a working SIL like the one in ietf-network-bridge and modify that after you spend some time figuring how it works.

**Comment by vggonzalez** [comment]
Alright, I'll go on and work in this through the next weeks. I will post here any updates.

**Comment by vlvassilev** [comment]
I added mininet testcase starting nodes controlled with netconfd instances [mininet/run.py](https://github.com/vlvassilev/yuma123/blob/master/netconf/test/netconfd/mininet/run.py) as example. You need something similar but instead of implementing the ietf-network-bridge-flows.yang module  [libetf-network-bridge-openflow.so SIL implementation using openvswitch OpenFlow controller API] (https://github.com/vlvassilev/yuma123/blob/master/example-modules/ietf-network-bridge/ietf-network-bridge-openflow.c) you will have to implement ietf-routing.

Notice that I use commit_complete callback instead of edit callback. It is more flexible since complex models usually depend on values spread in multiple branches of the tree.

**Comment by vlvassilev** [comment]
Now it is ready https://github.com/vlvassilev/yuma123/tree/master/netconf/test/netconfd/mininet

If you implement the ietf-routing SIL (similar to the implementation of ietf-network-bridge) you could add a router node to the topology.
