### ISSUE TITLE
netconfd will not start

### ISSUE THREAD

**Issue by samans** [vlvassilev/yuma123#64]
compiled on on Ubuntu 18.04.2 LTS following instructions here -> https://github.com/vlvassilev/yuma123/blob/master/README

When running the netconfd command, I get:

Starting netconfd...
Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
Copyright (c) 2013-2018, Vladimir Vassilev, All Rights Reserved.

netconfd version 2.12-0

Shutting down the netconfd server

E0:
   ../../../netconf/src/ncx/val.c:5836
   Error 2: NULL pointer

*** Total Internal Errors: 1 ***

Any suggestions to get this working?

**Comment by vlvassilev** [comment]
I found an issue in the README creating empty startup-cfg.xml and corrected it ([patch](https://github.com/vlvassilev/yuma123/commit/b03770b8298383133b2feeaabd48d036f8362d57)).

However if you were running:
/usr/sbin/netconfd --module=helloworld --startup=/tmp/startup-cfg.xml --log-level="debug4" --superuser="$USER"

You would have seen some extra output:

```
Error: Parse <load-config> failed and --startup-error=stop
Error: load startup config failed (xml reader EOF)
netconfd: init returned (xml reader EOF)

```
Let me know if your problem was not caused by the empty startup-cfg.xml file

**Comment by samans** [comment]
> I found an issue in the README creating empty startup-cfg.xml and corrected it ([patch](https://github.com/vlvassilev/yuma123/commit/b03770b8298383133b2feeaabd48d036f8362d57)).
> 
> However if you were running:
> `/usr/sbin/netconfd --module=helloworld --startup=/tmp/startup-cfg.xml --log-level="debug4" --superuser="$USER"`
> 
> You would have seen some extra output:
> 
> ```
> Error: Parse <load-config> failed and --startup-error=stop
> Error: load startup config failed (xml reader EOF)
> netconfd: init returned (xml reader EOF)
> ```
> 
> Let me know if your problem was not caused by the empty startup-cfg.xml file

That was it!  Thanks.

**Comment by APCBoston** [comment]
This issue appears resolved; can it be marked closed?
