### ISSUE TITLE
Problem with using command "edit-config".

### ISSUE THREAD

**Issue by serega911** [vlvassilev/yuma123#73]
Hi all.
I'm trying to play with helloworld example. But I have a problem with using command "edit-config".
Such error occurred - Error: cannot assign value to non-leafy obj 'input'.

**Steps to reproduce.**

1. YANG model
```
helloworld.yang
```

2. Netconf server is started with:
```
netconfd --module=helloworld --startup=/tmp/startup-cfg.xml --superuser=${USER}
```

3. Config file example:
```
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<helloworld xmlns="http://helloworld.com/ns/helloworld">
<message>Hello World!</message>
</helloworld>
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
</nacm>
</config>
```

4. CLI output:
```
edit-config target=candidate error-option=rollback-on-error config=/tmp/startup-cfg.xml

Error: cannot assign value to non-leafy obj 'input'
Error: invalid value (target = =candidate error-option=rollback-on-error config=/tmp/startup-cfg.xml)
Error in the parameters for 'edit-config' command (invalid value)
```

Thanks in advance
    Sergii.

**Comment by vlvassilev** [comment]
Check this [fix](https://github.com/vlvassilev/yuma123/commit/f4e6615e91acc64812bcc8ee166900629e9d3b97)

Now your command line (with correction) works.
$config=@/tmp/startup-cfg.xml
edit-config target=candidate error-option=rollback-on-error config=$config

**Comment by serega911** [comment]
Thanks.

Could you please also help me with the wollowing:

1. Is there any another availeble option for "target parameter"? It seems that writable-running doesn't work:
```
edit-config target=writable-running config=$config

Error: choice config-target in container target does not have any child nodes named 'writable-running'
Error: invalid value (target = writable-running)
Error in the parameters for 'edit-config' command (invalid value)
```

2. What is the purpose of "error-option" parameter? It seems that it always does rollback.

**Comment by vlvassilev** [comment]
1. I do not use writable-running. That said one reason for target=running (not target=writable-running) does not work probably because you do not have the writable-running feature enabled on the server you connect to (https://tools.ietf.org/html/rfc6241#page-37). I do not use writable-running (and you should not too unless you have a real reason). I can't provide support for writable-running mode.

2. Correct. The same behavior have confd and OpenDaylight. IMO error-option is under defined by design (rfc6241) and only rollback makes sense.

**Comment by serega911** [comment]
Thanks!
